name: fxtm
description: FXTM Stock List App Shell
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  dio: ^5.8.0+1
  flutter_bloc: ^8.1.3  # Для Cubit
  equatable: ^2.0.5  # Для сравнения объектов
  web_socket_channel: ^2.4.0  # Для WebSocket
  fl_chart: ^0.63.0  # Для графиков
  intl: ^0.18.1  # Для форматирования дат
  shared_preferences: ^2.2.0  # Для кэширования
  pretty_dio_logger: ^1.3.1
  logger: ^2.0.2
  freezed_annotation: ^2.4.4
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.2.1

dev_dependencies:
  freezed: ^2.5.7
  build_runner: ^2.4.6
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  mocktail: ^1.0.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
