name: fxtm
description: FXTM Stock List App Shell
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  dio: ^5.8.0+1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  web_socket_channel: ^2.4.0
  fl_chart: ^0.63.0
  intl: ^0.18.1
  shared_preferences: ^2.2.0
  pretty_dio_logger: ^1.3.1
  logger: ^2.0.2
  freezed_annotation: ^2.4.4
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.2.1
  connectivity_plus: ^6.1.3

dev_dependencies:
  freezed: ^2.5.7
  build_runner: ^2.4.6
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  mocktail: ^1.0.4
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  coverage: ^1.11.1

flutter:
  uses-material-design: true
  assets:
    - .env
